# -*- coding: utf-8 -*-
"""Comparing_images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MyBDUVseJvoGPygBESpkKdpncvXa-tcy
"""

import cv2

from google.colab.patches import cv2_imshow

from google.colab import files

# In Python, when we work with lots of numbers, especially in things like images (which are just huge grids of numbers!), we need a special 'super-brick' helper.

# That helper is called NumPy (pronounced 'Num-Pye')

import numpy as np

#Upload Your Images for Direct Comparison

image1 = cv2.imread("/content/tiger fall 01.jpg")

image2 = cv2.imread("/content/tiger fall 02.jpg")

# Get the dimensions of image1
height1, width1, _ = image1.shape

# Get the dimensions of image2
height2, width2, _ = image2.shape

print(f"Image 1 dimensions: {width1}x{height1}")
print(f"Image 2 dimensions: {width2}x{height2}")

#Images Must Have Matching Dimensions

image1 = cv2.resize(image1, (222, 296))

image2 = cv2.resize(image2, (222, 296))

# Performing the Bitwise XOR Operation

xor_image = cv2.bitwise_xor(image1, image2)

cv2_imshow(xor_image)